version: "3.9"

services:
  backend:
    build:  .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: arley123
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    networks:
      - app-net

  db:
    image: postgres:16
    container_name: postgres-jwt
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASWORD: arley123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net
networks:
  app-net:

volumes:
  pgdata: